### ISSUE TITLE
Automatically set `Rightarrow`

### ISSUE THREAD

**Issue by varkor** [jonschz/tikz-nfold#2]
At the moment, `nfold=1` is not permitted. This means `nfold` should only be used when `Rightarrow` is used (and, indeed, there are graphical issues if it is not used). Therefore, it would make sense for the `nfold` parameter to automatically set this option.

**Comment by jonschz** [comment]
Thank you for the suggestion. `tikz-nfold` can be used on arbitrary TikZ paths and is thus not restricted to `tikz-cd`, while `Rightarrow` is a `tikz-cd` feature. What would be your expected behaviour here? One idea that comes to my mind is for `nfold` to set `Rightarrow` depending on whether we are in a `tikzcd` environment (if that is possible).

**Comment by varkor** [comment]
Ah, I had overlooked that, it's a good point. I think that overloading the behaviour in a `tikz-cd` context specifically would be surprising behaviour. This behaviour would need to be implemented in `tikz-cd` itself (making use of `tikz-nfold`), so that would be the appropriate place to report it; I'll close this issue.

(I suppose that if #3 is implemented, then `double distance` will automatically be set, which would mean no package error. A user would still have to use `Rightarrow` to get the correct arrowhead, but it would be an improvement.)
